spring:
  application:
    name: ${APPLICATION_NAME}

harry:
  username: ${USERNAME}
  password: ${PASSWORD}

#sap¡¨Ω”≈‰÷√
sap:
  jco:
    provider:
      destName: ABAP
      ashost: 10.1.118.73
      client: 140
      sysnr: 06
      lang: zh
      user: test
      passwd: test
      pool_capacity: 10
      peak_limit: 50